### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fabrixpo** [BitMEX/sample-market-maker#102]
Tried (a lot of times!) to install the bot following the instructions both in venv and normally, on a fresh debian 8 installation but got always the same error. I believe the error is due to some stupid python configuration thing but as I'm not a python guy, I'm unable to address it. Maybe you can help me. I created a fresh new debian install just for that. Followed the minimal instructions to install and configure but when I try to run marketmaker I get these errors:

`
*marketmaker "XBTUSD" Traceback (most recent call last): File 
"/Library/Frameworks/Python.framework/Versions/3.5/bin/marketmaker", line 9, in <module> load_entry_point('bitmex-market-
maker==1.3', 'console_scripts', 'marketmaker')() File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-
packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/__init__.py", line 21, in run from market_maker import market_maker         
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/market_maker.py", line 11, in <module> from market_maker import bitmex File 
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/bitmex.py", line 12, in <module> from market_maker.ws.ws_thread import BitMEXWebsocket File 
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/ws/ws_thread.py", line 10, in <module> from market_maker.settings import settings File 
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/settings.py", line 25, in <module> userSettings = import_path(os.path.join('.', 'settings')) File 
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/settings.py", line 19, in import_path module = importlib.import_module(filename, path) File 
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 981, in _gcd_import File "<frozen 
importlib._bootstrap>", line 931, in _sanity_check SystemError: Parent module '.' not loaded, cannot perform relative import
`

Please help! 
![bacdeca1-05b7-4a4a-93cd-5dcdedc5555a](https://user-images.githubusercontent.com/38443590/39096272-f7030a28-464d-11e8-8bd3-673c63a47312.jpg)

**Comment by ryanfox** [comment]
It looks like you might have some issues with what version of Python you're running. What do you get if you run `pip -V`?

**Comment by fabrixpo** [comment]
`fabrizio@inari:~$ pip3 -V
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)`

**Comment by ryanfox** [comment]
Looks like you're not running the same version of python you installed it in:

    File "/Library/Frameworks/Python.framework/Versions/3.5/bin/marketmaker"
