### ISSUE TITLE
realised PNL

### ISSUE THREAD

**Issue by ricriga** [BitMEX/sample-market-maker#105]
Hi Ryan, the endpoint `/position realisedPnl` shows daily PNL. Does the endpoint to view PNL since opening the position exist? thx

**Comment by ryanfox** [comment]
Realised PnL is calculated by average entry price and the price which you sell at:
https://testnet.bitmex.com/app/pnlGuide#Perpetual-Contracts

**Comment by ricriga** [comment]
Ok sure, but that realised PnL can change for founding also.
I was hoping there was a API endpoint to get PNL since opening the position as web interface bitmex.com. Thx anyway.
