### ISSUE TITLE
marketmaker setup error

### ISSUE THREAD

**Issue by ak9250** [BitMEX/sample-market-maker#106]
marketmaker setup
Traceback (most recent call last):
  File "/usr/local/bin/marketmaker", line 11, in <module>
    sys.exit(run())
  File "/Library/Python/2.7/site-packages/market_maker/__init__.py", line 16, in run
    copy_files()
  File "/Library/Python/2.7/site-packages/market_maker/__init__.py", line 36, in copy_files
    except FileExistsError:

I already tried running with 

pip3 install bitmex-market-maker
Requirement already satisfied: bitmex-market-maker in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from bitmex-market-maker)
Requirement already satisfied: websocket-client in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from bitmex-market-maker)
Requirement already satisfied: future in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from bitmex-market-maker)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->bitmex-market-maker)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->bitmex-market-maker)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->bitmex-market-maker)
Requirement already satisfied: idna<2.7,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->bitmex-market-maker)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from websocket-client->bitmex-market-maker)

**Comment by rohitgehe05** [comment]
try using a virtualenv

**Comment by ryanfox** [comment]
You're running the program in a different Python environment than the one it's installed in:

```
pip3 install bitmex-market-maker
Requirement already satisfied: bitmex-market-maker in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages

File "/Library/Python/2.7/site-packages/market_maker/init.py", line 36, in copy_files
```

You need to run the market maker with python3. A virtualenv should help with that, and is a good idea for running python applications in general.

**Comment by ak9250** [comment]
@ryanfox @rohitgehe05 thanks i got it working after pip install virtualenv

**Comment by ak9250** [comment]
I wanted to add for ubuntu 16.04 even after getting virtualenv i am getting this error

Traceback (most recent call last):
  File "/usr/local/bin/marketmaker", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/market_maker/__init__.py", line 16, in run
    copy_files()
  File "/usr/local/lib/python2.7/dist-packages/market_maker/__init__.py", line 36, in copy_files
    except FileExistsError:
NameError: global name 'FileExistsError' is not defined
