### ISSUE TITLE
How can I use indicators?

### ISSUE THREAD

**Issue by BernatGV** [BitMEX/sample-market-maker#122]
Hello,

Maybe someone introduced this issue previously but I didn't see any information about that. I'm trying to make a BitMex bot and starting with python and market-marker but here I can make sell and buy orders but I don't know how to use the indicators.
There is someone that knows if I can extract "live" indicators data for my bot purpose? If I can't, it would be great if you explain to me some indications or ways to do it.

Thanks!

**Comment by AlexADittrich** [comment]
Hi BernatGV, 
Can you provide an example or more detail about this request?

**Comment by BernatGV** [comment]
Hi. Yes for sure.

For example. I put the MFI indicator on my plot chart. Supose that I want to buy when the line's indicator crosses the 0 line and sell when it crosses 80.

![image](https://user-images.githubusercontent.com/39464569/41548971-b0f27074-7324-11e8-875c-3017d1a2aca8.png)


I don't want only a bot that makes a buy/sale transaction. I want to make my bot more intelligent and apply on it more data like this MFI indicator to tell the bot when is that i want it to buy or sell or anything like close position when it pass through some value line.


Thank you for your support,
I hope I explained what I want my bot to do.

**Comment by AlexADittrich** [comment]
Thanks for clarifying. This is not an issue. What you are asking is for additional functionality, or a request for instruction on how to implement additional functionality.
