### ISSUE TITLE
Bitmex APi export quote

### ISSUE THREAD

**Issue by 0relmely** [BitMEX/sample-market-maker#130]
Can you share me the formula to export quotes from Bitmex api ? 
i will try something 

thanks

![image](https://user-images.githubusercontent.com/34755801/42180668-5f799032-7e38-11e8-9379-79646008e619.png)

**Comment by AlexADittrich** [comment]
https://www.bitmex.com/app/apiOverview

**Comment by ryanfox** [comment]
Retrieving quotes is beyond the scope of this market maker. For historical quote data, see the API explorer (such as your screenshot above) or the API connectors repository. [The Python client is here,](https://github.com/BitMEX/api-connectors/tree/master/official-http/python-swaggerpy) and there are other languages supported in that repository as well.
