### ISSUE TITLE
How to query OHLCV data?

### ISSUE THREAD

**Issue by akowalsky** [BitMEX/sample-market-maker#136]
I'd like to make a custom trading strategy based on historical data.
Specifically, I'd like to query updated OHLCV data  - let's say, last 60 one-minute candles - while running the market-maker bot, but I can't figure out how to do it. 
Could you please help?

**Comment by ryanfox** [comment]
For other API queries you want to use the api-connector. There is a python client [here.](https://github.com/BitMEX/api-connectors/tree/master/official-http/python-swaggerpy)

**Comment by Joshuaatt** [comment]
Hi ryanfox, what do you mean by "open and close don't apply". How do you specify a timeframe for high and low?

**Comment by akowalsky** [comment]
Thanks a lot, actually I found a super-simple solution [here!](https://www.reddit.com/r/BitMEX/comments/82niy1/how_do_i_get_bucketed_trades_from_the_rest_api/)

**Comment by evert** [comment]
open and close is a bit weird for an exchange that doesn't close

**Comment by STRML** [comment]
"open" and "close" are the open and close of the time bucket (i.e. 1D, 1H, or 1M), not the closing price of an instrument.

**Comment by evert** [comment]
Do you need both though? Or is close from the last interval == open from the next?
