### ISSUE TITLE
custom_strategy ImportError: cannot import name 'bitmex' from 'market_maker'

### ISSUE THREAD

**Issue by SaleProperly** [BitMEX/sample-market-maker#139]
I have successfully installed market maker via the "getting started" instructions in the README.

I am on Mac OSX 10.10.5

I can successfully run "marketmaker XBTUSD" using DRYRUN=True on testnet and get the expected output.

What I am having trouble with and don't understand how to do is running the custom strategy.

Executing the following:

`python3 market_maker/custom_strategy.py`

gives the following error:

```
Traceback (most recent call last):
  File "market_maker/custom_strategy.py", line 3, in <module>
    from market_maker.market_maker import OrderManager
  File "/Users/MYUSERNAME/python_projects/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
ImportError: cannot import name 'bitmex' from 'market_maker' (/Users/MYUSERNAME/python_projects/market_maker/market_maker.py)
```

Can someone explain step-by-step what has to be done to execute a custom strategy?

Thank you.

**Comment by chillz561** [comment]
i am having the same problem to

**Comment by Kalelv45** [comment]
Same here aswell.
Somebody could help please

**Comment by nursetta** [comment]
As of 8/29/18 I was getting the same issue. Running OSX 10.13.6. I was able to resolve this in the following manner:
1.) Created new directory. 
2.) Cloned this github repo to that directory.
3.) Created virtual environment in said directory: `python3 -m virtualenv env`
4.) Activated virtual env: `source env/bin/activate`
5.) Copied _settings_base.py from market_maker folder out to your sample-market-maker main folder. This is the same spot where you should see some config files and one called marketmaker. rename the newly copied folder to settings.py
6.) Open the marketmaker file mentioned above. copy and paste the following: `#!/usr/bin/env python

# from market_maker import market_maker
# market_maker.run()
from market_maker import custom_strategy
custom_strategy.run()`
7.) In terminal run `python3 marketmaker`

Your custom code should now execute

**Comment by ryanfox** [comment]
Instead of running the custom strategy directly (`python3 market_maker/custom_strategy.py`), create a script to run it from the top-level directory, similar to `marketmaker` (note no extension):

    from market_maker import custom_strategy
    custom_strategy.run()

**Comment by SaleProperly** [comment]
ryanfox has the best correct answer. Thank you.
