### ISSUE TITLE
How to keep orders on error/disconnection?

### ISSUE THREAD

**Issue by talarrr** [BitMEX/sample-market-maker#147]
Could someone kind please tell me how to keep orders on error/disconnection? Bot automatically cancels all orders on error/disconnection. 
I'm very green and I guess I need to edit the area below but it's not something I really understand. 

> def exit(self):
>         logger.info("Shutting down. All open orders will be cancelled.")
>         try:
>             self.exchange.cancel_all_orders()
>             self.exchange.bitmex.exit()
>         except errors.AuthenticationError as e:
>             logger.info("Was not authenticated; could not cancel orders.")
>         except Exception as e:
>             logger.info("Unable to cancel orders: %s" % e)
> 
>         sys.exit()

Thanks!

**Comment by cofibit** [comment]
Try to comment the self.exchange.cancell_all_orders()

`    def exit(self):
        logger.info("Shutting down. All open orders will be cancelled.")
        try:
            # self.exchange.cancel_all_orders()
            self.exchange.bitmex.exit()
        except errors.AuthenticationError as e:
            logger.info("Was not authenticated; could not cancel orders.")
        except Exception as e:
            logger.info("Unable to cancel orders: %s" % e)

        sys.exit()`

**Comment by ryanfox** [comment]
Keep in mind [this from the README:](https://github.com/BitMEX/sample-market-maker/blob/master/README.md#bitmex-market-maker)

> BitMEX is not responsible for any losses incurred when using this code. This code is intended for sample purposes ONLY - do not use this code for real trades unless you fully understand what it does and what its caveats are.
This is not a sophisticated market making program. It is intended to show the basics of market making while abstracting some of the rote work of interacting with the BitMEX API. It does not make smart decisions and will likely lose money.

This application is an example for experienced developers. You should only use it if you fully understand the implications of running or modifying it. There are many resources online for beginner programmers, but this is not an appropriate place for it.

Closing as this ticket is beyond the scope of this repo.
