### ISSUE TITLE
Unable to find settings-XBTUSD.py

### ISSUE THREAD

**Issue by achalofficial** [BitMEX/sample-market-maker#152]
No Such File or directory is being discussed in the readme...

![screen shot 2018-08-21 at 9 51 11 pm](https://user-images.githubusercontent.com/19564842/44414809-5f704d80-a58c-11e8-9108-bf69aff17e86.png)

Help me to solve the issue...

**Comment by AlexADittrich** [comment]
How did you install?

**Comment by oisinmacgiollachuda** [comment]
I'm getting the same error (having previously been able to install fine for ages) now, installing via "pip install bitmex-market-maker"

**Comment by achalofficial** [comment]
using pip3 install  bitmex-market-maker

**Comment by RishabhKhatri** [comment]
How do we create the setting-symbol.py file? It is not being created during the setup as of now.

**Comment by achalofficial** [comment]
I Found an issue #83, but any specific solution is not provided though. According to that, the market maker opts for the settings.py if it does not find setting-symbol.py... the problem is with the connection to WebSockets... that's another issue... #148
