### ISSUE TITLE
importlib.reload(module) is it out of date?

### ISSUE THREAD

**Issue by beeflowers287** [BitMEX/sample-market-maker#156]
I get the following error on first run. Please advise. 

File "/Library/Python/2.7/site-packages/market_maker/settings.py", line 20, in import_path
    importlib.reload(module)  # Might be out of date
AttributeError: 'module' object has no attribute 'reload'

**Comment by beeflowers287** [comment]
I think this might be a duplicate
**
pip3 install bitmex-market-maker

**Comment by righteyeofra** [comment]
I got the same error....

**Comment by anakratis** [comment]
> I get the following error on first run. Please advise.
> 
> File "/Library/Python/2.7/site-packages/market_maker/settings.py", line 20, in import_path
> importlib.reload(module) # Might be out of date
> AttributeError: 'module' object has no attribute 'reload'

You need to use Python 3.5 or higher, as noted in the README (it looks like you're attempting to run the script on 2.7). `importlib` was favored in 3.4, replacing the old `imp` module.

**Comment by Botalov1982** [comment]
I installed Python 3.6.5, and i have same problem....

**Comment by combstraight** [comment]
Getting the same problem.  I have python 3.x installed but when I run marketmaker on terminal, it uses python 2.7.

**Comment by Botalov1982** [comment]
I fix this using this code:
sudo ln -fs /usr/bin/python3.6 /usr/bin/python3
pip3 install bitmex-market-maker
marketmaker setup
pip install bitmex-ws

**Comment by anakratis** [comment]
> I installed Python 3.6.5, and i have same problem....



> Getting the same problem. I have python 3.x installed but when I run marketmaker on terminal, it uses python 2.7.

Remember that just installing 3.5+ doesn't mean you're installing over 2.7. You will still end up using 2.7 if you run `python`. You need to tell your machine to differentiate between 2.7 and 3.5+. This is typically done using `python3`. A little Google work will tell you how to do it.

**Comment by ryanfox** [comment]
Correct, this is a python version issue. Python3 is the only supported platform.
