### ISSUE TITLE
Can't able to get start 

### ISSUE THREAD

**Issue by ragupathis** [BitMEX/sample-market-maker#158]
I followed the below steps as per the documentation guidelines, but I get an error in terminal.

1) Create a Testnet BitMEX Account and deposit some TBTC.
2) Install: pip install bitmex-market-maker. It is strongly recommeded to use a virtualenv.
3) Create a marketmaker project: run marketmaker setup
This will create settings.py and market_maker/ in the working directory.
4) Modify settings.py to tune parameters.
Edit settings.py to add your BitMEX API Key and Secret and change bot parameters.
Note that user/password authentication is not supported.
5) Run it: marketmaker [symbol]

![screen shot 2018-09-18 at 1 19 56 pm](https://user-images.githubusercontent.com/5587483/45672490-f0aff100-bb45-11e8-8efa-7f8b5eb5ce9e.png)

I found the below line in documentation to get start., but unable to locate where to put the DRY_RUN=True.

Run with DRY_RUN=True to test cost and spread.

Help need to start the Bitmex with testnet. Thanks in advance.

**Comment by kelonye** [comment]
Use python3

**Comment by nazimbeyy** [comment]
how did u resolve?
