### ISSUE TITLE
401--signature is wrong??

### ISSUE THREAD

**Issue by cxf739** [BitMEX/sample-market-maker#163]
always report 401, how to resolve this???
![image](https://user-images.githubusercontent.com/8044844/46244650-96037880-c414-11e8-8f5f-442b0b5806d8.png)

![image](https://user-images.githubusercontent.com/8044844/46244642-5f2d6280-c414-11e8-91c2-63ada89ce91a.png)

![image](https://user-images.githubusercontent.com/8044844/46244646-7409f600-c414-11e8-8223-965785d56245.png)

**Comment by bendelo** [comment]
Have you entered a valid API key for the environment you are using (testnet vs www)?

**Comment by cxf739** [comment]
> Have you entered a valid API key for the environment you are using (testnet vs www)?

yes, testnet api key

maybe signature is wrong ?  or parameters of requests.Request() are wrong 。。。

**Comment by bendelo** [comment]
For a `GET` request try sending `query` instead of `postdict`

**Comment by cxf739** [comment]
> For a `GET` request try sending `query` instead of `postdict`

Thank you very much! It works!
