### ISSUE TITLE
Placing orders on Altcoins contracts on Bitmex

### ISSUE THREAD

**Issue by hTrap** [BitMEX/sample-market-maker#167]
I was trying place buy \/sell orders on altcoins on bitmex but there is no provision to pass a symbol through to converge orders, it takes XBTUSD by default.
 In the current codebase is there a way to place orders on altcoin contracts?

**Comment by bendelo** [comment]
Just edit `SYMBOL` in your settings.py

**Comment by hTrap** [comment]
What if I want to run it on multiple symbols at a time? Should I initialize exchange object with every symbol inside CustomOrderManager?
