### ISSUE TITLE
How to enable custom_strategy, install on Fedora 28

### ISSUE THREAD

**Issue by BruceBushby** [BitMEX/sample-market-maker#175]
I know this is not the first time this question has been asked, however its still not clear to me. I'm also a python novice which is probably why. The best answer I found was:
https://github.com/BitMEX/sample-market-maker/issues/139

But deleting/editing settings.py doesn't make sense so hoping to detail my setup which may benefit others and help me understand how to implement custom_strategy.

Fresh Fedora 28 build
Install Python3 packages 
Install git package

Run the following script to setup virtual environment and install bitmex-websocket and marketmaker
*creates ~/work/
*deletes ~/work/bitmex/

cut------------------------------------------------------------------------
#!/bin/bash

# ~/work 
mkdir -p ~/work;cd ~/work

# Clear any previous bitmex  
rm -rf ~/work/bitmex ; mkdir bitmex; cd bitmex

# Setup python3 virtual env
/usr/bin/py3-virtualenv env 

# Activate python3 virtual env
source env/bin/activate

# Create git location and clone repos
mkdir git; cd git

# Clone bitmex-websocket
git clone https://github.com/joliveros/bitmex-websocket.git

# Fix setting.py, Python install bitmex-websocket
cd bitmex-websocket
sed -i 's/from pip./from pip._internal./g' setup.py
python ./setup.py install
cd ../

# Clone sample-market-maker
git clone https://github.com/BitMEX/sample-market-maker.git

# Python install sample-market-maker
cd sample-market-maker
python ./setup.py install
cd ../
 
# Setup sample-market-maker
cd ../
marketmaker setup

# add API keys to ~/work/bitmex/settings.py 
# update path: PATH="~/work/bitmex/env/bin:$PATH" 
# Source env: source ~/work/bitmex/env/bin/activate
# Run marketmaker:
# cd ~/work/bitmex 
# marketmaker
cut------------------------------------------------------------------------

(env) [bruce@bitmex bitmex]$ ll
total 8
drwxrwxr-x 5 bruce bruce   82 Nov 16 13:36 env
drwxrwxr-x 4 bruce bruce   57 Nov 16 13:36 git
drwxrwxr-x 6 bruce bruce  189 Nov 16 13:36 market_maker
-rw-rw-r-- 1 bruce bruce 5163 Nov 16 13:37 settings.py
(env) [bruce@bitmex bitmex]$ 

(env) [bruce@bitmex bitmex]$ which marketmaker
~/work/bitmex/env/bin/marketmaker
(env) [bruce@bitmex bitmex]$

(env) [bruce@bitmex bitmex]$ marketmaker
2018-11-16 13:37:52,500 - INFO - market_maker - BitMEX Market Maker Version: v1.1

2018-11-16 13:37:52,501 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-11-16 13:37:52,501 - INFO - ws_thread - Authenticating with API Key.
2018-11-16 13:37:52,502 - INFO - ws_thread - Started thread
2018-11-16 13:37:53,503 - INFO - ws_thread - Connected to WS. Waiting for data images, this may take a moment...
2018-11-16 13:37:55,207 - INFO - ws_thread - Got all market data. Starting.
2018-11-16 13:37:55,207 - INFO - market_maker - Using symbol XBTUSD.
2018-11-16 13:37:55,207 - INFO - market_maker - Order Manager initializing, connecting to BitMEX. Live run: executing real trades.
2018-11-16 13:37:55,208 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-11-16 13:37:55,208 - INFO - bitmex - sending req to https://testnet.bitmex.com/api/v1/order: {"filter": "{\"ordStatus.isTerminated\": false, \"symbol\": \"XBTUSD\"}", "count": 500}

So thats marketmaker running on (Fedora 28) in 5min

Now how to implement a custom_strategy.py ? 

I like the framework in terms of websocket-auth, ordering, logging etc .... I would like to continue running the "marketmaker" command but have it run "custom_strategy.py" .... any tips?

Thanks
Bruce

**Comment by anakratis** [comment]
Hey Bruce,

You can actually call custom_strategy.py from market_maker.py. If you open market_maker.py and scroll to bottom you'll see `run()` function. Within this function or within `run_loop()` you can call `CustomOrderManager` class by importing it at the top with `from market_maker import custom_strategy`.

**Comment by BruceBushby** [comment]
Hi Anakratis 

Thanks for the help, much appreciated! 

I gave up trying to use "custom_strategy.py" and started hacking "market_maker.py"  with good success and probably a better way to learn how to use marketmaker. It really is a fantastic little framework and a nice example using python.

Posting some notes from yesterdays "hack session" in case it helps other novices.

Python installs marketmaker into "site-packages", placing en "executable" in the python environments "bin" directory. The executable is a python script using python/package/load_entry points 

# which python
(env) [bruce@bitmex bitmex]$ which python
~/work/bitmex/env/bin/python
(env) [bruce@bitmex bitmex]$ 

# list bitmex site-package
(env) [bruce@bitmex bitmex]$ ls -l ~/work/bitmex/env/lib/python3.6/site-packages/bitmex_market_maker-1.5-py3.6.egg/
total 0
drwxrwxr-x 2 bruce bruce 154 Nov 17 10:00 EGG-INFO
drwxrwxr-x 6 bruce bruce 269 Nov 18 09:05 market_maker
(env) [bruce@bitmex bitmex]$ 

# site package entry points
(env) [bruce@bitmex bitmex]$ ls -l ~/work/bitmex/env/lib/python3.6/site-packages/bitmex_market_maker-1.5-py3.6.egg/EGG-INFO/entry_points.txt 
-rw-rw-r-- 1 bruce bruce 50 Nov 17 10:00 /home/bruce/work/bitmex/env/lib/python3.6/site-packages/bitmex_market_maker-1.5-py3.6.egg/EGG-INFO/entry_points.txt
(env) [bruce@bitmex bitmex]$ 
(env) [bruce@bitmex bitmex]$ cat ~/work/bitmex/env/lib/python3.6/site-packages/bitmex_market_maker-1.5-py3.6.egg/EGG-INFO/entry_points.txt

[console_scripts]
marketmaker = market_maker:run

(env) [bruce@bitmex bitmex]$ 

#  market_maker:run  is inside site-packages
# ~/work/bitmex/env/lib/python3.6/site-packages/bitmex_market_maker-1.5-py3.6.egg/market_maker/

(env) [bruce@bitmex bitmex]$ cat ~/work/bitmex/env/lib/python3.6/site-packages/bitmex_market_maker-1.5-py3.6.egg/market_maker/__init__.py 
import argparse
import os

import shutil


__version__ = 'v1.5'


def run():
    parser = argparse.ArgumentParser(description='sample BitMEX market maker')
    parser.add_argument('command', nargs='?', help='Instrument symbol on BitMEX or "setup" for first-time config')
    args = parser.parse_args()

    if args.command is not None and args.command.strip().lower() == 'setup':
        copy_files()

    else:
        # import market_maker here rather than at the top because it depends on settings.py existing
        try:
            from market_maker import market_maker
            market_maker.run()
        except ImportError:
            print('Can\'t find settings.py. Run "marketmaker setup" to create project.')


def copy_files():
    package_base = os.path.dirname(__file__)

    if not os.path.isfile(os.path.join(os.getcwd(), 'settings.py')):
        shutil.copyfile(os.path.join(package_base, '_settings_base.py'), 'settings.py')

    try:
        shutil.copytree(package_base, os.path.join(os.getcwd(), 'market_maker'))
        print('Created marketmaker project.\n**** \nImportant!!!\nEdit settings.py before starting the bot.\n****')
    except FileExistsError:
        print('Market Maker project already exists!')
(env) [bruce@bitmex bitmex]$ 
(env) [bruce@bitmex bitmex]$ 


# Run directory 
(env) [bruce@bitmex bitmex]$ 
(env) [bruce@bitmex bitmex]$ pwd
/home/bruce/work/bitmex
(env) [bruce@bitmex bitmex]$ 
(env) [bruce@bitmex bitmex]$ ls -l
total 8
drwxrwxr-x 5 bruce bruce   82 Nov 17 10:00 env
drwxrwxr-x 4 bruce bruce   57 Nov 17 10:00 git
drwxrwxr-x 6 bruce bruce  189 Nov 17 10:08 market_maker
drwxrwxr-x 2 bruce bruce   37 Nov 17 11:15 __pycache__
-rw-rw-r-- 1 bruce bruce 5164 Nov 17 11:15 settings.py
(env) [bruce@bitmex bitmex]$ 
(env) [bruce@bitmex bitmex]$ ls -l market_maker
total 60
drwxrwxr-x 3 bruce bruce   123 Nov 17 10:00 auth
-rw-rw-r-- 1 bruce bruce 14226 Nov 17 10:00 bitmex.py
-rw-rw-r-- 1 bruce bruce   809 Nov 17 10:00 custom_strategy.py
-rw-rw-r-- 1 bruce bruce  1236 Nov 17 10:00 __init__.py
-rw-rw-r-- 1 bruce bruce 22877 Nov 17 10:03 market_maker.py
drwxrwxr-x 2 bruce bruce   207 Nov 17 10:00 __pycache__
-rw-rw-r-- 1 bruce bruce  5056 Nov 17 10:00 _settings_base.py
-rw-rw-r-- 1 bruce bruce  1199 Nov 17 10:00 settings.py
drwxrwxr-x 3 bruce bruce   128 Nov 17 10:00 utils
drwxrwxr-x 3 bruce bruce    64 Nov 17 10:00 ws
(env) [bruce@bitmex bitmex]$ 


You have to run "marketmaker setup" which creates "settings.py" and the "market_maker" directory.

When you run market maker, it will look for both the settings file and the directory ...... but it doesn't use that directory. I had to edit the files in the "site-packages"  .... perhaps a lack of python config/setup on my part.

**Comment by BruceBushby** [comment]
Closing, not an issue, comments explain question.
