### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by altcnews** [BitMEX/sample-market-maker#180]
hi all, 

got this error when running marketmaker XBTUSD

2018-12-28 11:29:40,405 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x7f466f214048>>: __on_message() takes 2 positional arguments but 3 were given

Appreciate for any helps.
thanks & Regards.

**Comment by qewerbit** [comment]
Edit  ws_thread.py in the line 208:
...
def __on_message(self, message):
..
on: def __on_message(self, **ws**, message):

**Comment by louisio95** [comment]
hey there, I modified the row but I still have the same problem...

**Comment by maker95** [comment]
Hi, have exactly the same problem I follow all the setup instructions but this error apperars.
wait your reply, thank you

**Comment by kimtg** [comment]
Using websocket-client===0.57.0 fixed the issue for now. (pip install websocket-client===0.57.0)
See also: https://github.com/bitvavo/python-bitvavo-api/issues/16#issuecomment-819598525

**Comment by ChenLi0830** [comment]
@kimtg thanks! That worked for me. The fact that this repo is not working out of the box makes me doubt about the quality of it. 🤔
