### ISSUE TITLE
Detail of order parameter

### ISSUE THREAD

**Issue by skynet0590** [BitMEX/sample-market-maker#203]
Hi there. I am trying to use BitMEX api to do a small app. Now I am discovering order api. But not sure how to use some field in order struct
Can someone let me know the value of order quantify. I see we have `orderQty`, `displayQty`, `simpleOrderQty`, `leavesQty`, `simpleCumQty` and `cumQty`.
Thank you

**Comment by STRML** [comment]
See https://www.bitmex.com/api/explorer/#!/Order/Order_getOrders, including the link to the FIX spec.
