### ISSUE TITLE
Run as a service on Ubuntu 18.04

### ISSUE THREAD

**Issue by ken4ward** [BitMEX/sample-market-maker#208]
How do I run this application on Ubuntu-18.04 as a service? Please, kindly help with specific steps/

**Comment by BKlun** [comment]
Same to me.. i do want to have basic settings and instructions ...
tnx

noob Blaz :)

**Comment by STRML** [comment]
Sorry, these Issues are for bugs in the project, not general support. However, you might get some relief looking around on support forums like askubuntu.com. For instance: https://askubuntu.com/questions/905749/running-python-script-as-a-service-and-start-on-system-start-up

**Comment by eyal352** [comment]
@ken4ward @BKlun Here's a service unit config file a wrote a while back. Hopefully it comes in handy for you or anyone else who comes across this. 

filename: **bitmexBot.service**
directory: **/etc/systemd/system**

`[Unit]
Description=Bitmex Bot Trader
After=network.target

[Service]
Type=simple
WorkingDirectory=/usr/local/bin/bitmexBot
ExecStart=/usr/local/bin/bitmexBot/startpy
User=bitcoin
Group=bitcoin
TimeoutSec=60
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target`
