### ISSUE TITLE
How to run custom_strategy.py

### ISSUE THREAD

**Issue by danielpengzuo** [BitMEX/sample-market-maker#209]
Hi,

Thanks for the well-written trading infrastructure. 
We are curious to know how to start the strategy inside custom_strategy.py.

Thanks a lot.

Best,
Daniel

**Comment by ChuckNorrison** [comment]
first build and install your marketmaker with your modified custom_strategy.py
if everything still works, you can modify your marketmaker file to import custom_strategy from market_maker and call custom_strategy.run() there. Remember to remove the obsolete lines.
