### ISSUE TITLE
Bad request for cancelling orders

### ISSUE THREAD

**Issue by jerreyz** [BitMEX/sample-market-maker#21]
Hello there,

Last week I was still able to run the sample market maker but now I 'm getting the following error:

`2017-10-31 14:07:40,680 - ERROR - bitmex - Error: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order?filter=%7B%22ordStatus.isTerminated%22%3A+false%2C+%22symbol%22%3A+%22XBTUSD%22%7D: {"error":{"message":"This request has expired - `expires` is in the past. Current time: 1509455267","name":"HTTPError"}}
`
 # Questions
>- shouldn't I be using __"wss://testnet.bitmex.com/realtime"__ for the base_url or is this only to be used for the websocket?
>- The Bitmex websocket in sample market maker is different from the one in the api-connector.
Which one should we take as the main source for further developing?

Kind regards

**Comment by STRML** [comment]
The error has to do with your clock being skewed from BitMEX's clock. Check your system's clock settings and resync with NTP servers (sometimes called "Internet Time).

As for your questions, `wss://` is for realtime data (websocket), `https://` is for requests.

Re: the endpoint in this module vs. api connectors, `testnet.bitmex.com` is a test exchange trading valueless Testnet Bitcoin, `www.bitmex.com` is the real deal. We highly suggest you develop and test on Testnet first, then move to the live site when you're very confident.

**Comment by jerreyz** [comment]
Great , thanks for the quick response !
