### ISSUE TITLE
None Data on Market Executions (Websocket) - certain Keys

### ISSUE THREAD

**Issue by nuggets-85** [BitMEX/sample-market-maker#214]
Hi,

This seems a reasonably recent thing - Im wondering if anyone else has experienced this.
On execution of "Market" orders - the ws_thread picks up the execution and recognizes an item needs to be parsed.  However the following code fails:

self.logger.info("Execution: %s %d Contracts of %s at %.*f" %
                                             (item['side'], contExecuted, item['symbol'],
                                              instrument['tickLog'], (item['price'])))

I've checked the content of the returned item and its clear the issue is that the item['price'] returns a NoneType:
Item: {'price': None, 'pegOffsetValue': None, 'orderID': 'b052d187-c43c-14a1-f6ab-d19d901196a5', 'displayQty': None, 'stopPx': None, 'ordRejReason': '', 'settlCurrency': 'XBt', 'clOrdID': '', 'orderQty': None, 'timestamp': '2020-04-15T19:18:06.674Z', 'cumQty': 0, 'transactTime': '2020-04-15T19:18:06.674Z', 'workingIndicator': False, 'symbol': 'XBTUSD', 'pegPriceType': '', 'multiLegReportingType': 'SingleSecurity', 'avgPx': None, 'simpleLeavesQty': None, 'side': '', 'execInst': 'Close', 'ordStatus': 'New', 'ordType': 'Market', 'clOrdLinkID': '', 'simpleOrderQty': None, 'timeInForce': 'ImmediateOrCancel', 'account': 31624, 'currency': 'USD', 'text': 'Position Close from testnet.bitmex.com', 'simpleCumQty': None, 'leavesQty': None, 'contingencyType': '', 'exDestination': 'XBME', 'triggered': ''}

Its interesting that some Keys are populated (such as transact time and orderID).  When I use the interactive API on the bitmex website to check the order - all of the keys are populated with the correct data - which if returned on the item in the ws_thread handler - would not cause any issues.

Im curious to find out if anyone has seen this issue recently or if its only happening to me.

Notes: I am running a custom strategy and have made some changes in ws_thread.py
I have checked my Limit orders - the item data on those is fine.

Any comments are greatly appreciated.

Kind Regards

**Comment by lambdademy** [comment]
I have the same issue

**Comment by buvelle** [comment]
on __on_message() method in ws_thread.py,
`# Update this item.
item.update(updateData)`
by moving this two lines above
`# Log executions`
solved the issue in my case.
I guess BitMex doesn't give us the price data anymore when each order is added.

**Comment by nuggets-85** [comment]
> on __on_message() method in ws_thread.py,
> `# Update this item.`
> `item.update(updateData)`
> by moving this two lines above
> `# Log executions`
> solved the issue in my case.
> I guess BitMex doesn't give us the price data anymore when each order is added.

This fix also worked for me - I left the original two lines in place and copied them in where you suggest above "# Log executions".
Possibly something Bitmex will fix - otherwise hopefully this fix is good enough.

**Comment by STRML** [comment]
Thanks. The bot is not expecting other activity on the account, but I have patched this behavior so it doesn't crash.
