### ISSUE TITLE
multiple tickers

### ISSUE THREAD

**Issue by JayDeng2837** [BitMEX/sample-market-maker#22]
Hi,

what is the correct manner to subscribe multiple securities in topic orderbook10?

I tried throwing a list of ["'orderBook10:XBTZ17"","orderBook10:ETHZ17"] but it seems i am only receiving XBT market data.

Thanks.

**Comment by ryanfox** [comment]
It looks like you're misquoting the arguments. Make sure you have the right number of quote characters, and match single- vs. double-quotes.

In any case, this is an issue for https://github.com/BitMEX/api-connectors. Closing.
