### ISSUE TITLE
amend on exchange is not atomic and can result in multiple fills for the same order

### ISSUE THREAD

**Issue by MarkRBest** [BitMEX/sample-market-maker#23]
Hey, I have been using a modified version of your market maker and I think its pretty great. You saved me a tonne of time so thank you. There is something that you should know about with the bitmex exchange that caused me issues.  When you amend an order via order/bulk the exchange doesn't check if the order was filled before moving it, this means if the exchange is busy you can get multiple fills from the same order. In the market maker currently you don't keep information about the current state of orders and if they were successfully cancelled or amended. This is only an issue if the exchange response time is greater than settings.LOOP_INTERVAL but when things get really crazy it is possible to blow your risk limits but placing a lot more orders than you intended to. The fix is to have a state engine in the order manager that keeps track of the messages sent to the exchange and then maps these onto the state of the order to avoid sending multiple messages if you have not had a response from the first.

**Comment by jerreyz** [comment]
Hey there Mark, I'm working on a modified version myself.
Do you intend on sharing  this state engine with the general public?


Kind regards,
Jeroen

**Comment by MarkRBest** [comment]
Hi Jeroen, The direct issue I had was fixed by a change made on the 2nd of November which changed the use of leavesQty in the amend message to orderQty. If you check the change log you will see it. This means you shouldn't get multiple fills and at least for now meant I could focus on not writing a state engine for the order manager. I wouldn't mind sharing that part at least if/when it's done, I am not sure exactly how that would work since I don't think my version would merge with the original any more due to the extent of the changes.

**Comment by bendelo** [comment]
This is already fixed:
https://github.com/BitMEX/sample-market-maker/commit/2cb1cf67e0e94b5c017d56f8074534545e49ce1c
