### ISSUE TITLE
Websocket error "can only concatenate str (not "int") to str"

### ISSUE THREAD

**Issue by fatcharlie13** [BitMEX/sample-market-maker#245]
Hello,

I'm trading on bitmex since 2019 using the websocket client. It is the same python module used in the sample-market-maker.

Everything worked fine until march 27, 2023. But since then I sometimes get the following error "can only concatenate str (not "int") to str" directly as websocket error message.

I'm using an older version of the websocket client (1.2.3). As mentioned before without getting the error. Only thing I recognised: there was an issue with the websocket that day and a fix that mentioned CancelAllAfter. But I don't use that.

So the question is: What changed that day? There may be a problem in the websocket client, so the real error cannot be processed due to an internal concat error. But I couldn't find any sign of it in the websocket module.

**Comment by DanishAlsayed** [comment]
Hi,

Thanks for raising this. Can you please provide more information and context on the error? Stack trace would be helpful.

Thank you!

**Comment by fatcharlie13** [comment]
Hello [DanishAlsayed](https://github.com/DanishAlsayed),

thank you for your reply. Here is the simple code I use for errors from the websocket client. Nothing special:

````
def on_error(self, ws, error_msg):
     print(f"ERROR - Websocket Error | {error_msg}")
````

Output (as mentioned, this sometimes appears since march 27, 2023):
>> ERROR - Websocket Error | can only concatenate str (not "int") to str

Other errors are displayed correctly, e.g.

>> ERROR - Websocket Error | Connection to remote host was lost.

I don't know if I can trace the websocket module. I'll check that.

**Comment by DanishAlsayed** [comment]
Thanks, so you have received the string `can only concatenate str (not "int") to str` from the WS directly? What were you subscribed on? WS trace could help.
