### ISSUE TITLE
Error - ws_thread [WinError 10054]

### ISSUE THREAD

**Issue by ShervinDD** [BitMEX/sample-market-maker#30]
Hi, I have a bot that updates prices every 30 secs using the market-maker code. It works fine 99% of the time.

Usually every 24-48hrs of continuous running, I get the following error:

ERROR - ws_thread - [WinError 10054] An existing connection was forcibly closed by the remote host
INFO - ws_thread - Websocket Closed

After that, the prices don't update and I have to restart the bot.

**Comment by ShervinDD** [comment]
Different error but same outcome. Price no longer updates and I have to restart the bot.

I use the market maker bot to get prices and submit orders for another strategy.

![noupdate](https://user-images.githubusercontent.com/32007993/33413083-6b717a74-d5e3-11e7-9618-33c225897817.png)

**Comment by cowthinker** [comment]
I do have the same error more than once a day. The server is just overloaded sometimes I guess. I worked around the issue by scripting a quick check every 3 minutes and restart if necessary lol

**Comment by ShervinDD** [comment]
hey @cowthinker , good idea! That's what I'll probably do. I don't think I can DM you on github, but can you DM me on Twitter? Twitter: @ShervinD
