### ISSUE TITLE
Shutting down all open orders will be canceled.

### ISSUE THREAD

**Issue by kenan3507** [BitMEX/sample-market-maker#31]
![screenshot_13](https://user-images.githubusercontent.com/27431211/33238767-eb399a44-d2a4-11e7-8a54-5df3246a1043.png)

I can not solve this problem for two days. I'm glad you helped me. Thank you

**Comment by bendelo** [comment]
What is the problem exactly? If you want it to actually submit those orders then stop running it in dry run mode.

**Comment by kenan3507** [comment]
First problem i have 2 TXBT on testnet, second problem "All open orders will be canceled" 
Last and biggest problem for the first time in my life I use python and i cant speak good english. Thank you :)

**Comment by kenan3507** [comment]
![screenshot_14](https://user-images.githubusercontent.com/27431211/33238885-a3e06ed6-d2a7-11e7-9228-4bf320b269eb.png)
Dry Run mode was open

**Comment by kenan3507** [comment]
When i false Dry Run 
![false](https://user-images.githubusercontent.com/27431211/33238941-cd180c7c-d2a8-11e7-8f72-3f51ab657dd8.png)
