### ISSUE TITLE
__on_close() takes exactly 2 arguments (4 given)

### ISSUE THREAD

**Issue by JayDeng2837** [BitMEX/sample-market-maker#33]
my "on_close" function actually looks like this:

    def __on_close(self, ws):
        self.logger.warning('Websocket Closed.')
        self.exit()

not sure why i am getting this error "__on_close() takes exactly 2 arguments (4 given)"

has anyone seen similar error?

**Comment by STRML** [comment]
Might be an update in the underlying websocket lib that passes more arguments. I'll take a look. Regardless, the app was about to close anyway.

**Comment by STRML** [comment]
Hmm, their docs still read that as a single argument (two if a member of a class): see https://github.com/websocket-client/websocket-client. Make sure your packages are up to date.

**Comment by cowthinker** [comment]
I have a similar error:
TypeError: exit() takes 1 positional argument but 3 were given

I installed the package from github with the link above and restarted the
bot, nothing changed.
websocket-client (0.44.0)

I'm using Python 3.6.2

**Comment by JayDeng2837** [comment]
I was using websocket-client(0.44.0).  
I ran the test_client below and it returned no error on my system(py2.7, ubuntu 16.04).
https://github.com/websocket-client/websocket-client/blob/master/examples/echoapp_client.py

this leads me to believe that the problem might be related to the close_frame that BITMEX sent while close.

**Comment by ryanfox** [comment]
Couple things:
- Is there a stack trace, longer error message, anything else when this error comes up?
- What command are you using to run the program, and when does the error come up?
- Python 2 is not going to be supported going forward, try Python 3.5+
