### ISSUE TITLE
BitMEX connector will not retry ordering on 503 error

### ISSUE THREAD

**Issue by Eteage** [BitMEX/sample-market-maker#35]
It looks to me like the BitMEX REST API connector will not retry placing an order (which uses POST) on a 503 error, which happens frequently when placing an order during times of heavy volatility:
https://github.com/BitMEX/sample-market-maker/blob/61f5d6766d9b6a19fa3cd3f79d9f1a7f1ee65f8b/market_maker/bitmex.py#L228-L233

This is contrary to the official BitMEX recommendation:

> To help improve responsiveness during high-load periods, the BitMEX trading engine will begin load-shedding when requests reach a critical queue depth. When this happens, you will quickly receive a 503 status code with the message “The system is currently overloaded. Please try again later.” The request will not have reached the engine, and you should retry after at least 500 milliseconds.

https://blog.bitmex.com/api_announcement/scheduled-maintenance-november-9-2017/

**Comment by ryanfox** [comment]
Retrying would likely run into a 503 error again. The default loop interval is 5 seconds - the market maker will try to place new orders then.

**Comment by rrsturua** [comment]
yes but my terminal on mac crached :( after 503 error :(
