### ISSUE TITLE
PnL

### ISSUE THREAD

**Issue by davidjcooper** [BitMEX/sample-market-maker#44]
I have been looking through the API docs at Bitmex, but cannot see how to add a simple PnL for open trades. Any advice please?

**Comment by ryanfox** [comment]
Can you be more specific? What are you trying to add PnL to?

**Comment by davidjcooper** [comment]
Hey Ryan, thanks for the response. It is more a general question to the bitMEX api really. 
I would like to show the running realised and unrealised PnL for the sequence.

**Comment by ricriga** [comment]
Hi Ryan, the endpoint `/position realisedPnl` shows daily PNL.  Does the endpoint to view PNL since opening the position exist? thx

**Comment by macd2** [comment]
> The endpoint `/position` returns fields `realisedPnl` and `unrealisedPnl`, those may be useful.

This is true but this is only based on market price and not on last price so it is pretty much useless...
