### ISSUE TITLE
Install as site-package

### ISSUE THREAD

**Issue by JSterz84** [BitMEX/sample-market-maker#45]
Hi guys, is it possible to install the market-maker as site-package and import it from there? When I run pip install . from the folder I am not able to import the module. Or does it simply not work as pip site-package?

**Comment by JMedon** [comment]
Hi I have the same issue in my VPS, I installed package in virtualenv but when I run the code I receive error:
"there is no module bitmex" and "ModuleNotFoundError: No module named 'market_maker.auth'; 'market_maker' is not a package"

**Comment by ryanfox** [comment]
The package is designed to be installed via `python setup.py install`.

If you need to install with pip, on the current dev branch you can install via `pip install -e .`

**Comment by ryanfox** [comment]
And now the package can be installed via `pip install bitmex-market-maker`.
