### ISSUE TITLE
websocket disconnect unable to connect all day

### ISSUE THREAD

**Issue by richardji7** [BitMEX/sample-market-maker#46]
Hi All,

Today is 1/8.  Is there something going on with both the production websocket and testnet websocket?  Get disconnected right away every time.  I got the connection, got market data, even got contracts created and see them popping up on the site.  But then immediately shutting down and everything canceled.

Thanks.

**Comment by richardji7** [comment]
Got back in on the real exchange.  Just testnet now.

**Comment by ryanfox** [comment]
Testnet is working normally right now. Closing in the absence of other information.
