### ISSUE TITLE
Exception: Attempted to recover from duplicate clOrdID, but order returned from API did not match POST.

### ISSUE THREAD

**Issue by JMedon** [BitMEX/sample-market-maker#48]
Hi
I dont know how to handle this exception and avoid exit but make restart or skip this exception.
Can you help?

`Exception: Attempted to recover from duplicate clOrdID, but order returned from API did not match POST.
POST data: {"symbol": "XBTUSD", "orderQty": -200, "price": 12558.5, "clOrdID": "mm_bitmex_Koc1va+9ScWjROsXLqXm0A"}
`

**Comment by ryanfox** [comment]
Is there more to the error message? There should be a `Returned order` as well.
