### ISSUE TITLE
400 Error Bad Request "This request has expired - 'expires' is in the past."

### ISSUE THREAD

**Issue by qwerqwer321** [BitMEX/sample-market-maker#49]
When I try to run the marketmaker I get this error, has anyone seen or encountered this error before? Thanks.

ERROR - bitmex - Unhandled Error: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order?filter=%7B%22ordStatus.isTerminated%22%3A+false%2C+%22symbol%22%3A+%22XRPH18%22%7D&count=500: {"error":{"message":"This request has expired - `expires` is in the past. Current time: 1516534870","name":"HTTPError"}}

**Comment by bendelo** [comment]
Your current time is wrong.

**Comment by qwerqwer321** [comment]
Thanks. How do I fix this? Do I change my system's time?

**Comment by qwerqwer321** [comment]
Which timezone do I change my computer's timezone to? I can't seem to get it working after switching to Hong Kong time, where I suppose Bitmex servers are.

**Comment by bendelo** [comment]
Your timezone is irrelevant. You need to set your system lock correctly.

**Comment by qwerqwer321** [comment]
What is system lock?

**Comment by qwerqwer321** [comment]
Sorry, I misread System clock. I changed it to be up to date. It works now. Thanks!

**Comment by biahoi** [comment]
Hi huys. I have the same issue. But I have already synchronized the system clock by changing things in settings.. But it works for a while then SOMETIMES still have that error: "..This request has expired - `expires` is in the past..."
