### ISSUE TITLE
Web Socket limit Issue 

### ISSUE THREAD

**Issue by shahidjalally** [BitMEX/sample-market-maker#50]
I'm using market maker bot since two months and it was working fine. Since last two weeks Im facing problem of Web Socket limits issue. While I open my account at website a pop-up appears that limits have set 20 connection per hour and my account making requests more than limits. I'm confused and don't know how I can resolve the issue. Please help me in this. I'm using shell script to run bot and this shell script first kill all python process and then start to bot. I have set this shell script / file in crontab and it run after each 10 minutes. Two weeks ago it was working smooth and I'm facing web socket limits issue.

**Comment by ryanfox** [comment]
You're hitting your rate limits: https://www.bitmex.com/app/wsAPI#Rate-Limits
You can connect a websocket 20 times per hour. If you keep the websocket open and don't close it, you shouldn't run into issues

**Comment by shahidjalally** [comment]
Thank you for reply. I have analyzed it already and resolve the issue with
exactly what you suggest.
