### ISSUE TITLE
auto-leverage value

### ISSUE THREAD

**Issue by ricriga** [BitMEX/sample-market-maker#52]
Hi, The endpoint /position leverage shows initial leverage only but i i didn't find value of auto-leverage as in web interface. Is it possible with api? thx for help

**Comment by ryanfox** [comment]
The `/position` endpoint returns a couple values `liquidationPrice` and `bankruptPrice`, that may be what you're looking for.

**Comment by ricriga** [comment]
starting from https://www.bitmex.com/app/autoDeleveraging i tried: 
`Effective Leverage = abs(position['markPrice']) / (position['markPrice']-position['bankruptPrice'])` but the value is not equal as effective leverage in web interface.
Any idea how get this value? Thx for help e for patience
