### ISSUE TITLE
how to send market order

### ISSUE THREAD

**Issue by JMedon** [BitMEX/sample-market-maker#53]
Hi I couldn't find market order code in sample-marker-maker or maybe I miss something.
Can you share me how to send market order?
I know that I can sens limit order with much higher price but it is not enough solution.

thanks

**Comment by STRML** [comment]
This is a market making application. Sending market orders would defeat its purpose. If you really do want to send a Market order via the API, see https://www.bitmex.com/api/explorer/#!/Order/Order_new.
