### ISSUE TITLE
websocket-apikey-auth-test.py key not byte encoded. 

### ISSUE THREAD

**Issue by SamSlate** [BitMEX/sample-market-maker#55]
sample-market-maker/test/websocket-apikey-auth-test.py

line 107, api key should be byte encoded before being passed to hmac 

`signature = hmac.new(bytes(secret, 'utf8'), bytes(message, 'utf8'), digestmod=hashlib.sha256).hexdigest()`
\^ from *APIKeyAuth.py*

**Comment by ryanfox** [comment]
This looks like a 2/3 issue. Python3 handles strings/bytes differently. This is fixed on the `dev` branch.

Make sure you edit `websotcket-apikey-auth-test.py` to have your API key and secret, and you have `BITMEX_URL` set to testnet or www correctly.
