### ISSUE TITLE
pip install is very broken

### ISSUE THREAD

**Issue by SamSlate** [BitMEX/sample-market-maker#57]
It could be I'm using it wrong, but as far as i can tell the version of *sample-market-maker* you get when you install via pip is completely busted.

**Comment by SamSlate** [comment]
(see closed issues)

**Comment by ryanfox** [comment]
Do you have any specific issues? What steps do you take to reproduce errors?

Verified this works in a fresh virtualenv just now:
```
pip install bitmex-market-maker
marketmaker setup
<edit settings.py with your API keys>
marketmaker
```

**Comment by SamSlate** [comment]
@ryanfox on a fresh instal running `marketmaker` from CMD does not reflect any changes made to the settings.py or any other files. You can see examples/screen caps in the closed issues tickets. (installing via the old method doesn't have these issues so i closed the ticket).

**Comment by ryanfox** [comment]
From your screenshot, it looks like your API key is incorrect. Double check your account has a valid API key + secret, and you're using the right one.

**Comment by SamSlate** [comment]
@ryanfox no dude. the key is fine, it's not reading *settings.py*, it's not reading ANY of the python files: that's the whole point. It ignores ALL changes. [Look at the arrows](https://i.imgur.com/bs0Wghl.png) notice what's missing from the console? When you run `marketmaker` it runs a program completely unrelated to the code in the *sample-market-maker* directory.

**Comment by SamSlate** [comment]
ok I found out what's happening: 

https://i.imgur.com/XDd0jS0.png

the program that's launched is actually being launched from programfiles, which is completely baffling to me *for a number of reasons*

1. `marketmaker` will not launch unless it's above a directory that contains a *market_maker.py* file **even though it ignores that file and pulls instead the file from the *market_maker.py* in programfiles**

2. by creating a file in programfiles I cannot edit it without administrative privileges

3. Why even create a local copy of *simple-market-maker* in the working directory if this entire directory is ignored **and can't even be run locally** because every include header points to `from market_maker import x`.  

This whole project has been incredibly frustrating to use. Why is everything linked as a package and not a local file? What does this accomplish??

**Comment by ryanfox** [comment]
It looks like your virtualenv isn't activated. So you'd be running the one in Program Files, and not the one in your virtualenv.

Try running `where marketmaker`.

**Comment by SamSlate** [comment]
...dude. if the only way this project works is when it's run in a virtual environment, you should include that in the readme file.
