### ISSUE TITLE
Failed orders getting queued?

### ISSUE THREAD

**Issue by mirvine** [BitMEX/sample-market-maker#63]
<img width="1185" alt="screen shot 2018-02-02 at 11 27 53 am" src="https://user-images.githubusercontent.com/1631163/35731156-750c0f08-080c-11e8-8154-6077d88283db.png">

Hello,

I am seeing some very strange order history when using the market maker. See attached screenshot. I am placing orders in the range of 50 to about ~500 contracts. Yet on my trade history, I see 3 much larger trades.

When I look in my order history, I see a big list of orders all going in at nearly the same time. In my logs, I see a lot of failures around these times (see below), most likely due to heavy load. So I assume that the failing orders are getting placed on a queue and are eventually filling.

2018-02-02 09:32:30,913 - WARNING - bitmex - Unable to contact the BitMEX API (503), retrying. Request: https://www.bitmex.com/api/v1/order/bulk 
 {"orders": [{"orderID": "737d0af9-a7bc-3254-a4c0-fe34103fadcb", "leavesQty": 513.0, "price": 8019.5, "side": "Buy"}, {"orderID": "ebc3b75d-6aad-5fca-ef62-d4a551741cb6", "leavesQty": 513.0, "price": 8346.0, "side": "Sell"}, {"orderID": "c5797343-7611-afc4-52da-d3416baa7e1e", "leavesQty": 363.0, "price": 8304.5, "side": "Sell"}, {"orderID": "03235f9f-a9ee-0d57-6dd4-3c5e9c71b797", "leavesQty": 363.0, "price": 8060.0, "side": "Buy"}, {"orderID": "fe5ecc00-2a3b-ea89-3713-6d31701b81e3", "leavesQty": 213.0, "price": 8263.0, "side": "Sell"}, {"orderID": "0806296c-c015-a7d1-a84d-822a793a9605", "leavesQty": 213.0, "price": 8100.0, "side": "Buy"}, {"orderID": "774770d3-dc07-3bc6-61b0-78f578a60a9e", "leavesQty": 63.0, "price": 8140.5, "side": "Buy"}]}

What's happening here? Are the failed orders getting added to a queue, then all getting executed together? How can I know if an order failed, or it's eventually going to be placed?

As you can see, this caused a massive spike in my position. I am only testing with small amounts so the value is not significant, but buying 18K of contracts when I have limited my max position to +/- 500 is a bit of a concern. I just want to understand how I can handle this better so I do not experience this issue when trading with larger amounts. How can I know an order placed? Is there a max time I can wait to be sure it was not placed, so I can retry?

Thanks!

**Comment by mirvine** [comment]
Will this fix resolve my issue? 
https://github.com/BitMEX/sample-market-maker/issues/23

I appear to be experiencing the exact problem as described ion that ticket.

**Comment by STRML** [comment]
503 errors are BitMEX system overload. 

What you have listed above is a 18k market buy. This adapter does not submit Market orders. I don't believe it came from this project - are you running anything else?

**Comment by mirvine** [comment]
The last one, for 18554 has no mm_bitmex. that was submitted through a 'close position' call. I added this to my local version as I wanted to close my position in some situations.

@authentication_required
    def close_position_market(self):
        """Close position at market price."""
        api = "order/closePosition"
        postdict = {
            'symbol': self.symbol
        }
        return self._curl_bitmex(api=api, postdict=postdict, verb="POST")

I'm not running anything else. 

The other orders are all limit orders. They have a mm_bitmex prefix. Were these caused by issue https://github.com/BitMEX/sample-market-maker/issues/23  ?

**Comment by STRML** [comment]
Yes, most likely. You should always be running the latest version.
