### ISSUE TITLE
help for step 3-4

### ISSUE THREAD

**Issue by Vict0r97** [BitMEX/sample-market-maker#65]
Hi guys,
so in step 3 i edit with notepad settings_base.py and add my API key et set dry_run = true
what is marketmaker [symbol meaning???], i don't undestand the symbol, and when i run bot nothing appear, i am doing the right way? i can't even test it

when i do "start marketmaker [symbol]" it cmd appears and disappears like nothing happened i need cleary how to do steps 3 and 4, it's not well explained for me.

Thanks for your help, Victor

**Comment by ryanfox** [comment]
You shouldn't edit `_settings_base.py`, instead edit `settings.py`.

`[symbol]` means substitute the instrument's symbol listed on BitMEX. For example, to use ETHXBT, run `marketmaker ETHXBT`. The symbol is optional, and defaults to XBTUSD. If you leave it off, it is the same as running `marketmaker XBTUSD`.

**Comment by Vict0r97** [comment]
That's ok, but in settings.py there is nothing to write whereas the code is in settings_base.
Thanks for the symbol ok ok
Plus what is base_URL??
i'm not clear at all

Thanks to you, Victor

**Comment by ryanfox** [comment]
You need to follow the directions to get set up: https://github.com/BitMEX/sample-market-maker/tree/dev#getting-started

**Comment by Vict0r97** [comment]
the problem is i don't understand the directions

**Comment by ryanfox** [comment]
This library is intended for developers - a certain level of experience with Python and programming is necessary to be able to use it.

You might try some python learning resources or [stackoverflow.](https://stackoverflow.com)

Closing this because it's not an issue with the library.
