### ISSUE TITLE
Why is the cumQty added to orderQty

### ISSUE THREAD

**Issue by DesignerFrames** [BitMEX/sample-market-maker#70]
`  to_amend.append({'orderID': order['orderID'], 'orderQty': order['cumQty'] + desired_order['orderQty'],
                                     'price': desired_order['price'], 'side': order['side']})`

In this line when you cycle through the open orders to see if they are worthy to amend them, for the new orders quantity you add the current.cumQty to the desired.orderQty, I am just wondering why this is because if your desired size is a 5000 contract position for example and it gets slightly filled for 500 contracts on the original order and then amended you end up with a order for 5500 contracts... I am not sure if I am missing the point but it would make sense to me if that was subtract instead?

Thanks

**Comment by bendelo** [comment]
It's not for new orders, its is for amending existing orders. If you amend orderQty to 5500 that will give a leavesQty of 5000.
