### ISSUE TITLE
probably a bug in the function get_price_offset(self, index)

### ISSUE THREAD

**Issue by yhyhUMich** [BitMEX/sample-market-maker#76]
https://github.com/BitMEX/sample-market-maker/blob/dd4071de84a7f46816ab58a8fd530750dc652b05/market_maker/market_maker.py#L298-L302
I found it out that when resetting the start_position, it may exist a bug.
should it be as follow since the original code doesn't handle the occasion when start_position_buy > start_position_sell?
```
if index > 0 and start_position < self.start_position_buy: 
     start_position = self.start_position_buy
 if index < 0 and start_position > self.start_position_sell: 
     start_position = self.start_position_sell 
```

**Comment by STRML** [comment]
If the buy position is higher than the sell position, that throws an audit error and shuts down (https://github.com/BitMEX/sample-market-maker/blob/dd4071de84a7f46816ab58a8fd530750dc652b05/market_maker/market_maker.py#L455)
