### ISSUE TITLE
Close all open positions on Unhandled Error

### ISSUE THREAD

**Issue by madnight** [BitMEX/sample-market-maker#78]
I think it would be a good idea to close all open orders / position if an unhandled error occured, otherwise the market-maker terminates and leaves unwatched position on the exchange.

https://github.com/BitMEX/sample-market-maker/blob/0ea988684a58e6713558fc6d4de1b2d3f79d9c74/market_maker/bitmex.py#L343

**Comment by STRML** [comment]
It should be doing that, see the atexit handler in the main file.

**Comment by madnight** [comment]
Ah okay i think that's `cancel_all_orders()` but what's with open positions? Lets say all orders are canceled but you have still left 200 open short positions, shouldn't theses be closed as well? I think it would could be dangerous to leave open positions on the exchange.

**Comment by STRML** [comment]
Two things: one, you can only have *one* position. Second, automatically closing it at market is likely more dangerous than not doing it. What if you have a hedge on another product or another exchange?What if there's not enough market liquidity to close at a reasonable price?

**Comment by madnight** [comment]
I agree that it might not be suitiable for everyone, but i think there should be at least an option for that. Another thing that i observed is that after some time all your money is already in an open position, hence the available balance is near zero and the bot terminates because it cannot open any more orders.

**Comment by STRML** [comment]
Because it is so dangerous there is no chance we'd implement it by default,
even behind an option. But the reason the code is open is so that you can
add your own logic. Just add it to the code if you need it.

**Comment by madnight** [comment]
Okay whats with my second question?

> Another thing that i observed is that after some time all your money is already in an open position, hence the available balance is near zero and the bot terminates because it cannot open any more orders.

Is that normal?

**Comment by STRML** [comment]
No, you should set long & short position limits so you don't quote above a certain size.

Again, this is open code, please check it out yourself & make changes where needed.
