### ISSUE TITLE
No import statement for the OS module used

### ISSUE THREAD

**Issue by joemaren** [BitMEX/sample-market-maker#9]
The OS module wasn't imported in the setup.py file, but was used in the "here" variable.
![bitmex](https://cloud.githubusercontent.com/assets/13188600/26492391/b698ce94-41c8-11e7-8f07-d1248506070e.png)

**Comment by STRML** [comment]
You are using a (very) old version of this project if you are seeing that error on line 5. On line 3, `dirname` is imported. Please pull and try again.

**Comment by joemaren** [comment]
Just realized the version was an old one. Pulled the changes. Thanks
