### ISSUE TITLE
too many request 403 (spammy order)issue

### ISSUE THREAD

**Issue by soultrain23** [BitMEX/sample-market-maker#95]
Basically bitmex is wonderful site but support is really not very good.
I try to make some bot using market marker for a few months and have a big problem.
It needs to lot of orders. So i make a orders very carefully. On the basis of Spam orders policy
(https://blog.bitmex.com/notice-regarding-spam-orders/ ) Request to sever in every 20 second.

If you use API for a while, it becomes disconnected and "too many request" errors are generated in the handshake section(when it start soon). The site is also closed. There's nothing I can do.
Support asks me the source, but nothing i can give to them.
Cause Same error occurs even if i use the source listed on the market maker github.

And the big problem is they didn't try to check it. When i ask them with my api key, account, what happened, i didnt nothing wrong basis on spam orders, other else. They ask me exectly same thing what i gave to them. 
what's your id? what's your happen? what's your api? here's spam order policy. 
copy and paste, copy and paste, copy and paste, copy and paste,copy and paste, copy and paste
They didn't care about a supporting. I got it. 

Now im stuck in this issue. Guess i have to solve that all by myself
Is there anybody like me?

2018-04-10 19:56:17,102 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-04-10 19:56:17,102 - INFO - ws_thread - Authenticating with API Key.
2018-04-10 19:56:17,102 - INFO - ws_thread - Started thread
2018-04-10 19:56:18,794 - ERROR - ws_thread - Handshake status 403 Forbidden
2018-04-10 19:56:19,119 - ERROR - ws_thread - Couldn't connect to WS! Exiting.

Testnet, or not is same. 

![aaaaaa](https://user-images.githubusercontent.com/34236803/38554619-397bc452-3cfe-11e8-97bc-5c8faa91d16b.PNG)

Now i guess they just hate me. I made up with Market Maker Sample source. wow~!

**Comment by ryanfox** [comment]
Information on limits can be found in the piece on spam orders above or [in the BitMEX docs.](https://testnet.bitmex.com/app/restAPI#Limits)

Clients that follow the guidelines described there will not be rate limited or banned.

**Comment by soultrain23** [comment]
the answer like that is reason why i bring up a problem
