### ISSUE TITLE
no place in settings.py to added API key and secret 

### ISSUE THREAD

**Issue by AlexADittrich** [BitMEX/sample-market-maker#96]
Hello, 
I started with powershell `pip install bitmex-market-maker`

then `marketmaker setup`

settings.py file is created, but I see no where for an API Key or secret to be placed.

my settings.py file reads
`from __future__ import absolute_import

import importlib
import os
import sys

from market_maker.utils.dotdict import dotdict
import market_maker._settings_base as baseSettings

def import_path(fullpath):
    """
    Import a file with full path specification. Allows one to
    import from anywhere, something __import__ does not do.
    """
    path, filename = os.path.split(fullpath)
    filename, ext = os.path.splitext(filename)
    sys.path.insert(0, path)
    module = importlib.import_module(filename, path)
    importlib.reload(module)  # Might be out of date
    del sys.path[0]
    return module

userSettings = import_path(os.path.join('.', 'settings'))
symbolSettings = None
symbol = sys.argv[1] if len(sys.argv) > 1 else None
if symbol:
    print("Importing symbol settings for %s..." % symbol)
    try:
        symbolSettings = import_path(os.path.join('..', 'settings-%s' % symbol))
    except Exception as e:
        print("Unable to find settings-%s.py." % symbol)

"# Assemble settings."
settings = {}
settings.update(vars(baseSettings))
settings.update(vars(userSettings))
if symbolSettings:
    settings.update(vars(symbolSettings))

"# Main export"
settings = dotdict(settings)

`

I also see a file called _settings_base.py

I am 
Windows 7
Phython 3.6.5

**Comment by ryanfox** [comment]
Go up a directory, edit the `settings.py` there.

**Comment by AlexADittrich** [comment]
Thanks a lot! That was very quick and that worked!

**Comment by vcreddy22** [comment]
Hi 
I am experiencing the same problem, what do you mean by move up a directory?

**Comment by AlexADittrich** [comment]
@vcreddy22  The folder before, or above, where your settings.py folder is. Look for another settings.py file there.

**Comment by vcreddy22** [comment]
i dont see a second settings folder 
![capture](https://user-images.githubusercontent.com/42252959/43927746-7ef0950a-9bfc-11e8-92e6-f311eff62450.JPG)

this all i see

**Comment by vcreddy22** [comment]
how do you stop running the bot?

**Comment by grantbelford** [comment]
Hi Alex and vcreddy22

Apologies but I don't follow how to find the 2nd settings.py file?

**Comment by grantbelford** [comment]
ah. API key & secret can be edited under settings_base.py
