### ISSUE TITLE
API KEY INCORRECT, COULDN'T CONNECT TO WS! EXITING

### ISSUE THREAD

**Issue by hogwartsjedi** [BitMEX/sample-market-maker#99]
Hello everyone, 
I installed the python scripts as instructed in the description. I created the testnet bitmex account, deposited some testnet bitcoins as well as created the API keys and secret. However when i try to run the bot with command "marketmaker XBTUSD", below is the error which i receive. 

![image](https://user-images.githubusercontent.com/38063483/38783586-087459ee-4115-11e8-8846-600347d5da2b.png)

Could anyone tell me what i could be doing wrong here? I tried deleting the API and regenerating a new set of keys. Is there any other alternate to properly run this, what could i possibly doing wrong here? Please advise, kind of noob here.

**Comment by HuSunshine331** [comment]
@wizcap hi
could you please tell me how to modify the settings.py?
I have do this

def import_path(fullpath):
    """
    Import a file with full path specification. Allows one to
    import from anywhere, something __import__ does not do.
    """
    path, filename = os.path.split(fullpath)
    filename, ext = os.path.splitext(filename)
    sys.path.insert(0, path)
    module = importlib.import_module(filename, path)
    importlib.reload(module)  # Might be out of date
    del sys.path[0]
    return module

API_KEY = "my-key"
API_SECRET = "my-secret"

userSettings = import_path(os.path.join('.', 'settings'))
symbolSettings = None

**Comment by AlexADittrich** [comment]
Try going up on directory from were your current settings.py file is. If you find a settings.py file in that directory, modify that one instead. #96

**Comment by ryanfox** [comment]
@AlexADittrich has the correct answer. Closing as a duplicate.

**Comment by TianDaGe** [comment]
@ryanfox 
Are you getting your current margin balance correctly on your bot?
